### ISSUE TITLE
Please provide higher quality tiles if possible

### ISSUE THREAD

**Issue by lexterror** [Pomax/mahjong#52]
I have trouble using the current tiles. If you can please provide higher quality tiles.

**Comment by Pomax** [comment]
Not unless you want to explain "trouble" means.

**Comment by lexterror** [comment]
I have problems seeing the tiles. You have a really great game! I think it would make a huge difference to have high quality tiles! 

Look here: https://github.com/FluffyStuff/riichi-mahjong-tiles

Thank you!

**Comment by lexterror** [comment]
Hi, I managed to change all the tiles to higher quality!!!

Here is my demo: http://elounge.org/mj/index.html

**Comment by Pomax** [comment]
I must admit, those look very ugly to me, but if that works for you, good on you. Just don't pass off my project as yours and have fun playing.

I can probably rescan my tiles (because that's what they are: literally the tiles I play with at home) at a 2x resolution so they're easier to see on modern high dpi screens, but probably not until later this week.

**Comment by Pomax** [comment]
I've filed https://github.com/Pomax/mahjong/issues/54 as implementation issue
