### ISSUE TITLE
Theme support in the future!

### ISSUE THREAD

**Issue by lexterror** [Pomax/mahjong#55]
It would be great if there was options to choose different tiles and tables. 

Thank you!

**Comment by Pomax** [comment]
- [ ] add localStorage-based settings
- [ ] add a tileset chooser
  - [ ]  followup: add a simple file-drop UI that can take a tile spritesheet and turn it into play tiles
- [ ] add a background/felt/bank chooser
  - [ ]  followup: add a simple file-drop UI for images for those

**Comment by Pomax** [comment]
@lexterror theming is now supported.

![image](https://user-images.githubusercontent.com/177243/123464999-6ae8ec00-d5a2-11eb-825b-8bb65598487d.png)

which gives you four options:

![image](https://user-images.githubusercontent.com/177243/123465022-73412700-d5a2-11eb-80e1-bb7c3ad082b3.png)

images must be 500kb or smaller (because localStorage only permits storing a few MB), and the tileset must be 9x5, like this:

![tileset](https://user-images.githubusercontent.com/177243/123465087-89e77e00-d5a2-11eb-8cfa-1740adb35f00.png)

that is:
- bamboo 1 through 9
- characters 1 through 9
- dots 1 through 9
- E, S, W, N, blank tile, green dragon, red dragon, white dragon, blank tile
- flowers 1-4, seasons 1-4, back-of-the-tile

All tiles _must_ have a 1px border around them, but can be any size as long as they're all the same size and the image is <500kb. In the case of the above example, each tile is 36x50, which means including its border it's 38x52, giving use a total image size of 38 * 9 = 342px by 52*5 = 260px.

**Comment by Pomax** [comment]
If you have ideas around improving the theming, feel free to file a new issue, and I can see what might be done.

**Comment by lexterror** [comment]
This is a really cool improvement! Thank you!

Im into Digital Art. I was thinking maybe I could submit a template or two! It would be up to you!
I thought that having some default options would be good as well! Im currently working with Inkscape on Android! Im thinking of designing modern looking tiles right now...

**Comment by Pomax** [comment]
presets might be useful, as long as the graphics are not license encumbered and you file the PR to add them into the repo (even if I write the code for loading presets from files using a simple preset picker, those files need to trace back to  you in case someone files a legal complaint. Not that I expect anyone to ever do, but it's one of those things you need to provision for when working on open contribution codebases)

**Comment by lexterror** [comment]
I put this together just now! I have it as a vector as well! Its kind of a "lighter" version of yours! If you are interested in the vector I can post!

![tileset](https://user-images.githubusercontent.com/16135535/123499586-bf718300-d605-11eb-9951-f495052256f3.png)

Thank you!

**Comment by Pomax** [comment]
That would definitely also need a different colour scheme, so let's see if I can also set up a "change the colours" something-or-other (they're all CSS variables, so it'd mostly be getting the color picker right)

**Comment by lexterror** [comment]
Ok, I am not sure what you mean by different color scheme! Im a bit slow in real life as well! But Im posting here the preview and svg! I tweaked it this morning!

![tileset](https://user-images.githubusercontent.com/16135535/123519716-0483cc80-d67b-11eb-958c-13b750202ba9.png)

The SVG:

https://drive.google.com/file/d/1PV_TicKNebkRE6js9hBZhPMt4bWmXfwH/view?usp=sharing

Thank you!

**Comment by Pomax** [comment]
I mean this is a little too jarring, and we need some more UI to actually change the CSS colors used by the game:

![image](https://user-images.githubusercontent.com/177243/123521144-aa2e4000-d669-11eb-9034-b7a7eaf089bf.png)

Also, in order to add the file I will need you to file a PR that adds this file to the `img` dir. The fact that you contributed it needs to be "on record" (I can't be the one adding it to the repo in this case, unless you can update the SVG to include comments with a copyright/license description and author field so that folks know I didn't steal it from somewhere ;)

I've filed #59 to hopefully address "customizing the non-image coloring" soon.

**Comment by lexterror** [comment]
Ok, I just finished the release version of the tileset! I also added the white dragon and fixed the colors of tile 3 and 4! Feel free to modify or adjust the colors of the tileset. This tileset is mostly a modification of fluffy tileset! Also, the author of the flowers and bird are unknown! They were free to download. And I just created the white dragon a few minutes ago!

![tileset](https://user-images.githubusercontent.com/16135535/123524645-be8a3100-d699-11eb-8b02-2743239e02ec.png)

The SVG:

https://drive.google.com/file/d/1gjivFlejuArITaF131j6ssuU1IlkbHIc/view?usp=sharing

Thank you!

**Comment by Pomax** [comment]
free to download doesn't mean "free" in the internet, though. Unless there was a CC or PD license or the like that came with them, I can't use them.

**Comment by lexterror** [comment]
https://github.com/FluffyStuff/riichi-mahjong-tiles (Attribution CC)

<a href="https://www.vecteezy.com/free-vector/flower">Flower Vectors by Vecteezy</a>
 (Attribution CC)

https://www.redbubble.com/i/sticker/Mahjong-Tile-Bird-yat-sok-by-thestreetslocal/53297948.EJUG5

The thing about not sharing in my opinion is that it limits people's full potential. If everything is owned, there is  people that are willing to leave you with nothing.

Thank you!

**Comment by Pomax** [comment]
I'm not going to argue copyright: it's idiotic and Disney is at the heart of the problem, but the law is the law, and I _have_ to abide by it. Whether I like it or not, in order to make sure I'm not culpable, I _have_ to ask you to show the content you're contributing is not license-encumbered (or if it is, that it's a kind of license that allows reuse/derivatives)

So thank you for those links, it looks like the flower vector link doesn't go to a specific set though, but just the general category. Also, that redbubble link is clearly not a free-to-use graphic, so if you used that, you'll have to find (or make) a different one if you're using it in your tile sheet.

**Comment by lexterror** [comment]
Hi, 

Im a bit discouraged! I was not aware of the legal information! I could design a new bird or find one with a CC: I just do not want to re-invent the wheel! It seems silly to me! I will look for a new bird or design one! Hopefully you can use it and if not I got to learn a few things!

Thank you!

**Comment by lexterror** [comment]
Ok, I was able to come up with this design! I was inspired by real chinese mahjong tiles! There is no logo for this design online. Its an original!

![phoenixnew](https://user-images.githubusercontent.com/16135535/123561362-f2d31f80-d775-11eb-855f-54be927f1292.jpg)

Let me know what you think!

Thank you!

**Comment by Pomax** [comment]
I know, it sucks when reality hits, but unfortunately once you start contributing to other people's repos, this is how it is =(

also that is an _amazing_ bamboo 1, might need a branch across to make it at least feel like it's still related to sticks/bamboo but that's awesome, nice job!
