### ISSUE TITLE
Small css glitch (Users Kong tiles are off vertically)

### ISSUE THREAD

**Issue by lexterror** [Pomax/mahjong#65]
I was playing a few games and noticed when the user composes a KONG the tiles are off vertically (They are half showing)

Thank you!

**Comment by Pomax** [comment]
If you mean this:

![image](https://user-images.githubusercontent.com/177243/137635904-65a33543-930a-4549-9639-98a71f0e2e31.png)

that's by design, any tile that was concealed at the time the kong was played will be rendered [as a half-tile](https://github.com/Pomax/mahjong/blob/master/src/css/tiles.css#L138-L141) because there are three different ways in which to play a kong:

1. you had a pung in  your hand, and claimed the fourth tile from a discard, thus being a concealed pung,
2. you had a pung in your hand and drew the fourth tile, this being a fully concealed kong, or 
3. you already had a pung on the table, and drew the fourth tile, with no concealed tiles.
